version: '3.8'

services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    image: python:3.10-slim
    working_dir: /app
    volumes:
      - ./backend:/app
    command: python app.py
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}

  user_management_service:
    image: python:3.10-slim
    working_dir: /app
    volumes:
      - ./backend/user_management_service:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8080
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=${JWT_SECRET}

  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: npm start
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}

volumes:
  mongo-data:
